# Generated by Django 4.1 on 2022-08-25 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wellcome',
            name='pub_date',
            field=models.DateField(default=1),
            preserve_default=False,
        ),
    ]
