# Generated by Django 4.1 on 2022-08-25 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_wellcome_pub_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wellcome',
            name='pub_date',
        ),
        migrations.AddField(
            model_name='wellcome',
            name='published_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
